### PR TITLE
Check for valid metadata on quantitySample to avoid crash from bad metadata from Withings blood pressure sample

### PR DESCRIPTION
**Pull request by sgilroy**
This addresses the crash described in https://github.com/Telerik-Verified-Plugins/HealthKit/issues/87

## Smoke Test
1. Install "Health Mate" from Withings
2. Login and add a blood pressure measurement (measurement can be added manually or from Withings blood pressure cuff)
3. Sync the measurement from Health Mate to the Apple Health app (HealthKit)
4. Query for blood pressure from an app using the https://github.com/Telerik-Verified-Plugins/HealthKit

### CODE REVIEW

**Comment by mgerstenblatt** [comment]
Any chance we can get this merged in?

**Comment by EddyVerbruggen** [comment]
Sure, it looks good to me, thanks @sgilroy -- I missed this PR for some reason, so thx @mgerstenblatt for pinging me. 👍

**Comment by mgerstenblatt** [comment]
thanks @EddyVerbruggen!  will you be bumping the version too?

**Comment by EddyVerbruggen** [comment]
Done. 0.5.4 is on npm.

**Pull request merged**
